sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
  - secure: HsT0oYod4FeeXNMwO07vGLsb92iyKqXm9zLba8GY/iS/CedCHQSGTD5sahtTZc95MCcZWBnAHAnWwauSgnUAV0bWHCouLSVJ5wLF2H5wLYQhY4Tfmvt9oJcsDqvjjbFxn2DVx0tdqciTupaxvxvW8qw6KXbPCjSmBWAZiP4bewMaKLFfjEBq+9wZO58rfXx72oFZnTQaefPc4idpRuKNDtM+vz6DsbPa15sD9UQcyxVjUUTH5Acr3g1d7bJJ47ES1Dxkryaye2J+zBiFMzt2785LeHuMHPEe3ZlvR8u08Fe5aT13Fvojy7Vf2sp2p+tv41DJPinM5GFiaS7lZbICl8ptYKoLbN7XNnb0MpHOnXvwG/Ce22SJOvh075CPS/nK7WOphm5tjofR3o3zeuHyi5cTtoX0XJ9c2j2cZrj+D9JSeX0pUQ3AS45KWmk1RsqLl3kTHkzHxT89JrPwNcLWycl8dYUXOJQ+tGqrVFVLJy4kimdyILfpol2/+yixcBtFf6xlx/QuxGCxbPXXvSNZP+hA+/6+r/GHbyWa7iEePPHeTzVACJ5+IKhDtF1WFqh87kE59F2gKkCAFbivy8PYO0IE8QEG5gHYllkNdd4aU05wOAMzgM1uHOq7xlNvcEiHTkY96HqzuxL4tYcTAfUi2wtO3c7p3j8EwRZv5xPAsbA=
  - secure: A1S7icOWwZL/7rs5R4VPpQwSpzXHHqJA+secGbmpoSboh7ypxpXbuCQJ4Jo/0fcBR4WrCwZExUJoCftIgSXROAZWIvM3ZIli4YC1ZG0ZbiGr3YsAMHFFBy7hLHLUNXABaReJzf22/6HEpnDdASbv2c7CPp9FQ/GRZLudlLB07j4Cu289xBrvz4KE6ualJiRedh6tVwnOsrFQhjfjkI0KOED0oIDoYBx+Ju3DVrpSv4E1rh9dzfc+2LLwtiEO9/Taa7bjhSxbij6wdvF7RCw03Vc8XAn/oLuF7m7neFk9ZqJpY/g/mXXAsDViULZSfnYE6ws3QmsfhehcIcEJscuWwODql0+KRfzIY6od5zP2oKLtrvVyFWg2RRek0kOKH+DoM5qhpRguqdVQcXsz0ruCvel8gyfLiDZU0w5dKZAcWdcRBCinv2O29xshTQsQYnzPZ9GsXVy9RhjMcOYU349PLFvyWEOqUmvgW9Rq0UmfgNZkpoPw5q6CR0SdnDpjRozz75DsI3G0fTCYkTonYynU6CMxqzSacKw3lIvnCbS1N9ReV7oiwF5lRwODLc8AnpZ1WAhBc4XonRULFvJJrDUTGTrRu7nNVsNynOBtLdIdQ2QEVCYeQm0wqUwvmRV4WMRz0sg8mARe/yDt1i9+f71UmLSUzw2wYCF22tUrnyNdisI=
before_script:
- cd image
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
