sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
  matrix:
  - secure: e9QZZpGoCvgH1G5E49H+amEV0mM4CZoGASGGP0dbrIWp6MtYL2dr3LYnZTnGfVGdZy/5IncnhR0yUHVpn1AaUVCS/l9bHMPBbeveu4cjyZgBxVHEqDhIrNcfxY/rggCBb9lHmso4qjV/pCROdyfaO3taTnzw6tJO63gXJDpz0v7BRjJOoxa2SSAoZzhzpepI9wIw2rPLpr5TBzbKFZKNhlPu3Ta4fFL1XiP00qgLk4LeXl1LlQeObTYiYFVFXlkwQY4A+yLExaOX6Me+ZDIGEZn5yokUdS285BPF8h3y7qCzku0ogOqtQtdrhsWqcfgxctZUHkjPOz1u2schYa6RnGLEzJTPMCJRwOlbeo/24U9YjWdQB4QK/CdEkT+DFuLwyW0PS/O54CdgMZ3EIsz2lDO3DsTjQ+QbQd93O/ihdOqDZKIoXed/obfBCmPHQD62zGXDJOMhmYbjQcZXMRtezhLWx+MeQ6rV1qD06XS2lwgZauoUrwspU6vxraUu4mtnsSi5KUNuJU67tRTEqOXLvbEgerXELW5XCy6gC/SWeoYpeBXLusHnKbX5A1eko9ZqrxKIHN04usZaLpRKmisB6t94PEhL2iTSDePewcK2RXkx1hX4/tdtVrP2jziW1GZFUR5U1ZtakHhVlgTfM82UHCRwMHGCkQabZCFIov6bZSw=
  - secure: KmYMhzKTMSDRj1EU7M4ZenLqt09pndBlTVJ2FlST2923QQeTjE0poYnfpMXkqVc6LeI30C5M15RNPJjakctyKG/8deeF5AsM3WmLyHvil80rlqPzmE9mS0YoWnrloDa4FAogT5Bmt3Btzt6bNJ/gVB9WMDwosjpGwuKMqi3GmVhmW6WWIL6/WFiYxqw4OnT1mtwn8BlQ0sorXn/acQ63yqXyrhknI5sGjbEwtXMkJsNqo8kfCue6Chfo2tJB3LVrPRUsYQLLfAeIKWCJNc0JtglK6TMGc2AYzmdzgdZAvYlVsrIbNGa4i3Ne0wd6ZwuyCS2hx5oSbIiYtOtgZ7xZ7wRfspHf3cSf6gIVEV/QGY0MTN14FWixCxphTeZGxcwzoTvM5zEzGJ4NwZMgb9Ts1Z9AVamPFd0LsBugDJD109UUOKh7FVd033lM72lT1rJbuDQPijEtAp1FnXhTT/GhPb4CSXxiNj7wj6Cj++SK6qNpR8Oed6I9F2Rzk6l+1nw+vsz7QjAuZeuEiAyfsIBTBSzTXWV9Nw5aVl2Si67i4ekaBgkkr2Sm3/SPBrOW+iqCy1qtBQpmJ6TfLhJBTCMYpkreD7J5Yd60VChoGgVLgcxB1RlPpZuxwkBX9yWjt2Wz7dGmRi2Wu6AROIXf82T9DX7Pz1vh6rLDMBfgp+ply3A=
before_script:
- cd image
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
