sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
  matrix:
  - secure: HcWlsnUhIkird2Zd+rx9AlY1ve1uAxjA/taN8ShycLX1b+kn+roFrOdxzrG+rcrAiM5iI30gu4mYkqr9MThAuGiXtivVcArLDFj9g3zLFqL9sq2BqhN/oiiwV1N/qfHz8YPhhg9p6rJjDYtLBjJ8XftU+l89EDqb1cqZ0WkEKnToDY+vUC+AczBh/T1XiwxMXCIgJw8TYePnr7pacoth6l1OGDPV3h3pLduHiEuM/QnO/Ilhq4PF2NaiDK/JJXf89WRSoN6YbYIhpVk20H7LWpvGAoDbGo1dr2+BZDEmNpp2o3ccCTAUpqi0zyMOgOj4P6Cbb1JqvLHiJEHv3/5ruFYXojeg7Y9uyYFukRET73sTWadEiStRpvB/US0EYFA0yUbE24ImXcrft0b4bmFImfQyYXO6qjwU8k8uUzje5ISayLtm4eY6amEc1dLzu33hvglOiRQkiA0MjN0A5KLN9l2yWEUFqREpPvvIb/iroRPXZATBMLzmcSq4K4IwvN/g8+2HDwHbxGI327lsNUhgUSPeMsVZVuiNCJgNGSIExsV+0CIhjfAfGNURCcrAW4Uew3DvbWyjnO11+tZ+K6O1dGaDjm0u8j2JtSZ1xOvfZ0uBu/Htmjd0fiA3qOxukZpN8FjjtLs+Fd/rfFerIE4ZMC3eKFx8iYYQWa8QVvdri/8=
  - secure: ESy2+VK4x7sL3C5gfag4Cfnu8pcVhf2S4XttjnJ2Lq4FiLfijUEA6HZzoX6ZJo48q4HMT8KdaKLvfrvJFFgZdk2DEtI+u9Q38sJHkYQrRB6C3rK9MgU9mRGD46ophJf+k6nlBClWfqn/8+Cgpkm0sJh45GOjFiWD0WLX8w+ncrU9b58FVmbs2KRpazv3fMr0yvvnATRjsL4AYUsE8DiN/RbyASTeiDwUTiA+mCPLTprpBd+5EWhoNUlBWfbX9mc70+j6PSFMlFb6b7dyt2xXyKAjG+zqq1dH+H2DTmiktXfY3rVbcW9vGso5gKSdCcI11SFlTxq7Qn3AS6ngM2b4Am6swEsktv4MqSrwUbXdFYZAR9v62pXQBKyWmnLk2Fzni1ENBhi1bMj33SKZ0QW8ImL9g3t5blfbtCgSo0rXw2zD05m4modu4uKHyh699pXGOxMBTva6C8g6UEGQ5z4XctIy1tzjWzGEQbiu5hKCPUjYUPXcTyf6D0YoMCZLk633ZMI+Em2uWW7zpuce8rTIVecTS/FXDrokMgLu08jp7vTG+Zd8RxdimfCu+kg9OEndlrD5zL/4CVBgk6iQ8FJfWZoKBmXGSZ2KHYmkEZ+cJOXMH49Y0q9iPD9U5qmoYhJGMIMZmnGqhWWVRQlCJ61F7HfRulzuAiriwxGT6RRYKGA=
before_script:
- cd image
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
