sudo: required
language: ruby
services:
  - docker
env:
  global:
    - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
    - secure: oWd5f/wys/ghq9mrKRTdHWy/E6Ofn4P2S8MUROPv32XynBQBCLb3DHy0jS7aS0P8w7HMJtJHM9fAQeMoZSW3To8ojJN9HEN9L3k1Rvs1ygrha9T9bPS4oOE0AMETfUabWziykdSM2LuRCF1FjHU5794ls235O2wnhmX7z6SFIlK8+D3AridiqU4fiLRSA+tVXgkg5u0IFFrEaKvOO6TjDi+8OEgPsS8sNcpar+q/QXD30WHlXqhCKSBxHaFj/XYSGPkeA2o7CloMvGFDIVuRPNM8pMHCUR90SppiZSSkvzTTciYZTFhfsAEUGB7aWE3Klto8Y1do258bT2d2h/rjKzHaWioIz4ZN+AJD4flfYytvnxpWMLgN0spzNRSs2wfUIilK1q9OvRaG2fPEcGtkXkqO1VP5mt+QwycjpHRiMzKPeJhh/wZDgG6HZ54+GddjlqJcCGwjksqpwfneS6MwMCj/VMwqY9DXKQUcy81jahCKfgUvzN9fBso7z5ta3lfUxf4CYjgn5+xXnQ5P9HucPcYMKkEvuMjEGxM/nKIB2kFqdrI/FvFCk578T9Rf9duObfhnZbiz78gLLS20R5js+hzeMRgi1VwrcI656jfflaZY9u5NSfrgmY/L1UIvPG/ngF+Tgpx2GIvFsYv5KlHL0m/m8daEY9Bfkus9O4mLM3Y=
    - secure: jvVQDG2Qsm2lhrLLJbfrTDZGKxhFVq8Dc6MqPpVDeSOMKuFKCwa0MGQZXgfQ2JssFefq3zvh4dBIRyRo9eceW8I6Q14MMR/C8ywqz4xaRac31SpcrOjVATVklTuFIGij11W+TRSK87q+Ld0trHgBJuUF6vmjK1XUKZyUvUZ/ejSKZc+sa/REtDPs0zrh/o848qeSam8uAdKwJi/FjA2rpsc3NE5O11GTgMHh6gEN8QHOZgzoZgeker9jfytI74MiIYp+qfKqjYuwxyAkc8QN977myhOtM+Q9ZU7wQ1RGh5Z8ylse7lZbknmp+vszKcUWxn6cLucTojf60Zn9+1kMavadtNPOYyLdPpqt36bQtaafvK1IP1R+nZBgUbkDvP9enwaKhUfX0KQl2lP4sKk5AVffDQzHBVUXfgoE6s5+85Fxs6SOHyx30oqmNzCS1i8Gm0tr3K6t8Oc3fYkQEXItd94jQDJruRndw9S614xncdl04nhVgrmH0TY3RYde31TZ+1fhfzNd3Od1CJT9yubttc+/orpZ3V5UEhCqVPJaokZiCt9daZQnjPc7Dv0PLLaul3XXVEeGnLZqPRxvOniiSd271gw2CNHOrsElIFYy38gOm65HKyN5TxnmZy4efvyDBKX4wPyIHTBva8ghWw0zLKQoruyNppx8muJQx+KDeIA=
  matrix:
    - DOCKERFILE_NAME="python"
    - DOCKERFILE_NAME="node"
before_script:
  - cd image
script:
  - docker build -t "$IMAGE_NAME" -f "Dockerfile.${DOCKERFILE_NAME}" .
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${DOCKERFILE_NAME}"
  on:
    branch: master
