sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
  - secure: VV1aYDJXM1fPGYHADFePSTQ97u2y4/KpPIxEW0Y0FzYKhEXdbEbUIVokrQpd29jcKBfTZC59RPoikcrWVsREtbtQ7RC/4WxkUCwimt0tCEOwJmxEHPfg47jpd+Dmk3gaM1x3Ku6eEo8IAUwyPF6RkMxAtFkLfNCmrnIsSqzIdBytLDKVAnLuu6rJKi5DNekiur5CeVHnyDXQZ6dg2AY+89NHz6NqMP4HZspdZX/f/QxhOzDD3fnimPF0Djs9+01bFLKgOY5m8Hh0TrDLF8I1pLE/7nWGAMNVwpmb/Un4bbJDXkRHgLpC901fFFkSMI/tJKf+1V/I29J6xJredAjNAbBgbdKyA2rj+0O1iB3sCt2Myosmc01aWB+l5HT7NfReEl08zXp9OunCnYwnYOi0hxBa/KY9C45vQZf9VYaHVuXh6mwUTQJlpTjbFARQ1pSAXIGvg6CGbjww2Uoyuj88axyIhawfgVq6Gril15IURkPNak/f6D+ptq+O0rbynxRhmsdsMvmLvqwWE9FbAPoylA2o3aCU6jSLb5CXW2C7zdljAsT/DVcxLkeD43gksGvhO54V4oX7JsiXvQRU3pmgnuBTkcAzf8PImAulqrS8l8qBy/qa3pqOt3O0nyryzk0QYUKVtFes9gnwMvu+MW8BRsBMOPzySiUcgm+m2DnEb30=
  - secure: dITpZ+DF12ghWkp0BkB7I6ccUGogV66b2J5oblASDN9kqFXW4/S6w6OeCGHVpOIwaP2gzSuFzzbh9WHdFnvlr7UDMthr/FcqaYUAzNliB94SArJTC+BBDVfnKPAWVoOPGy16Xs7ecVKArf4aVVwebYkvYjqLIi7fffBgROM9Ufk9JTkIFNZnA4Lbr0PIIGDYjgKfvC/eQpyiuTwOzpFXsoZylI1VSOa4eBoO+atqj6uAX0OTZ71qpeVjbgTfTjyjz5cYBhapKbwCklHzE+krU+dBROKMArmMPS3UJevvsiXDXwZsiO5FfIiMJbk5LK87qE8Mceju/sQVRYUgH/PGqnGb4npIzZwmMjUGubfb4WPGzA6UN4s23lsPLZ56qrwy1ajX+OndnbfnKSw1RnzeqV2Zpa28Lk/IYh0l7pO5Ak48/AqXDSyiXnQTDldfrrCx06jGz+767YbYpW7m445rafpMSLUto9370Zy5T6n2Z0+c2u0oaOvmrrguv0JM1M9h0eLzFYKnPAGMT4nKV1FoJE6iwmoTQEObf3t2cz+T/iwKGu8/vY92YxnTGt6K2J2HNlDH2dmeYTHoaCt/lXdTrcaIy2jJ5X8RpoOM/5uZ59eUqMSppYDWHzZvENzR7Ei0LIurQjvrJwZbPEFS61ypMqfVJZpU92lCRq29/kPOhZ4=
before_script:
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
