sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/gitlab-rcbot-runner
  - secure: c8tfjIPO1r2q+G77SNDngG/PQgdrEsa5VhAr0vWor5NIKkhyEhcONHZ1vuVjmuU4knfb6fTr9AyD73lNG+I9dEgAgkjmfEs5zyGuWaLW2CYhU5g+zAYm44ZTlFJY0Rvd+y4mRyqEBVC6gl89r9vTxlBwuu2AeYNSDsbXiDZLGVUCCS8lS35JCrQ4sn0NXr78u7+RU7rqOrIFLmqvWWOMfOdPRuS//2pe7OnIxEY7D4n0HfK6f1LCf3pnvJtfgaIp2bRmOxKm8BH3tLeJ6ZhOoRbEJxnDIoWp1HE4jxuCoSf57ew8YQz2EQGwc5iyk3FIOS3A4/7Ue4VR/rAMIusL7dXC4dq9WxYV8WtyZj27uf6YstyxDR5JYIu+S8lNWebnS8SOGIP7461cakuOnLDZzq7NpcKKrs4Pdz496nYTHdZJxhsy8VBHfiUbNsvbKRTHehvfXi5KVzhyMaVUkIRUAqQQkiRxcvWdZbilyYh98Tg46fgwkBghqjdBctjsqqwuoq9Xya4sl5NrRXUs9p8riHZadUrq8wERccLSMjy3AirCFiZScwqQowb3ifK6enGDxiJd69+Uv6TcDaZErivwYasJY+b2qTkPDN9ybt+jXPWvX18cX5ZeWAq605MFipq0vcpioSAgPDSsnm2TlbU87n9COtqONeB5/Uzmr+sia94=
  - secure: YZma624aVjpUAD8t/J9TyRAomXHlGxd/NAa1rIcDPJGWKhhBvaPCMx/+aEtM3yOu1Y2w9aNqzg90syxqfLaQ6hwaM6Q2jK13/j6xCRIl/hBHXXIOhoQfZjF7yo1vxc+QrYfV5ES5Wjij0hFedMSMLNG9iLO6mu9USmDXd0+mSsZ/pvg8kf6zQRnlKsUt5GMnXlz2Go1+NtliuH2O0jip3MweYKoJRCpo/N0JyfmbFql6YSS+OOw1veyKBOAgY9pMWEduiumNszyjrosmYlyzIdS5DXaSaMH6DnGLgmwOr5Hi+p88YGma/4JU8Qt3EBjmI2CTmb0s1ssI9OpOD0DV3miZZ1fotawKmltoqxsxr2uz9bEtF3brjiGYButMnIP0SUorwz13eeRU0FPulsWjnN4Bjrd43hLg+JQI2Fu0PCALNIewExqCw6QA8BmzSikXEcfnehiPjB3SlO5jR//57eMiFuVVa0cAxx6mxMYQz6o83hUvg13XD6Z10oIinxSQv0LBVf7UtWN7+NOnfFWd8Ulpe5l1m03Wl8Ad0pp/ORGGvf/JGYixrAg62Vu2AnrXbhAebxdWWFBz6BsaeO4Ye858nb59dbaFnWdUJnc4jj0KpB1m0zX16HQMWh7XUJZpQJa57SDlBgXYiUt9pWNLSvG5Xt/vrnyrJgIB6j6A9z4=
before_script:
- cd image
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
