name: Build gitlab-bot-runner

on:
  pull_request:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfileName: [python, node]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build & Push Image
        run: |
          cd image
          IMAGE_NAME=ringcentral/gitlab-rcbot-runner
          VERSION="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile.${{ matrix.dockerfileName }})"
          docker build -t "${IMAGE_NAME}:${{ matrix.dockerfileName }}${VERSION}" -f "Dockerfile.${{ matrix.dockerfileName }}" .